import React, { useEffect, useState } from 'react';
import { 
  Container, 
  List, 
  ListItem, 
  ListItemText, 
  Typography, 
  Grid, 
  Card, 
  CardContent, 
  Button, 
  Dialog, 
  DialogActions, 
  DialogContent, 
  DialogTitle, 
  TextField,
  Divider 
} from '@mui/material';
import { blue, grey, green } from '@mui/material/colors';

// Define the structure of a Player object
type Player = {
  id: number;
  rank: number;
  player_name: string;
  age: number;
  hits: number;
  year: number;
  bats: string;
  description?: string; // Optional description field
};

const App: React.FC = () => {
  // State to store the list of players
  const [players, setPlayers] = useState<Player[]>([]);
  // State to store the currently selected player
  const [selectedPlayer, setSelectedPlayer] = useState<Player | null>(null);
  // State to control the visibility of the edit dialog
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  // State to store data for editing a player
  const [editData, setEditData] = useState<Partial<Player>>({});

  // Function to fetch player data from the backend API
  const getData = async () => {
    try {
      console.log('Fetching and correcting data...');
      await fetch('/fetch-and-correct-data');  // Corrects data and fetches players
      console.log('Fetching players...');
      const resp = await fetch('/players');    // Fetch the list of players
      const json = await resp.json();          // Parse JSON response
      console.log('Players fetched:', json);

      // Sort players by year (descending) and by hits (descending within the same year)
      const sortedPlayers = json.sort((a: Player, b: Player) => {
        if (b.year !== a.year) {
          return b.year - a.year; // Sort by year first
        }
        return b.hits - a.hits; // Then sort by number of hits
      });

      setPlayers(sortedPlayers);  // Update state with sorted players
    } catch (err) {
      console.error('Failed to fetch data:', err);
    }
  };

  // useEffect to fetch player data when the component mounts
  useEffect(() => {
    getData();
  }, []);

  // Handle the click event on a player to fetch and display their details
  const handlePlayerClick = async (player: Player) => {
    console.log('Player clicked:', player);
    
    try {
        const resp = await fetch(`/player/${player.id}`);  // Fetch details of selected player
        const updatedPlayer = await resp.json();           // Parse the response

        setSelectedPlayer(updatedPlayer);  // Update state with player details
        setEditData(updatedPlayer);        // Set edit data with current player details
    } catch (err) {
        console.error('Failed to fetch player details:', err);
    }
};

  // Update edit data state when user inputs changes
  const handleInputChange = (field: keyof Player, value: string | number) => {
    setEditData(prevData => ({
      ...prevData,
      [field]: value,
    }));
    console.log('Updated edit data:', { ...editData, [field]: value });
  };

  // Function to fetch a description generated by an LLM for a player
  const fetchLLMDescription = async (player: Partial<Player>) => {
    try {
        const response = await fetch(`http://localhost:5001/generate-description`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(player),  // Send player data as JSON
        });

        if (!response.ok) {
            throw new Error('Failed to fetch LLM-generated description.');
        }

        const result = await response.json();  // Parse response
        console.log('Fetched LLM description:', result.description);  // Log the description

        return result.description;

    } catch (error) {
        console.error('Failed to fetch LLM-generated description:', error);
        return '';
    }
};

// Handle save action in the edit dialog
const handleSave = async () => {
  if (selectedPlayer && editData) {
      const updatedData = { ...editData };

      // Fetch and update the description with LLM-generated description
      updatedData.description = await fetchLLMDescription(editData);

      if (updatedData.description) {
          console.log('Saving updated player data:', updatedData);

          fetch(`/player/${selectedPlayer.id}`, {
              method: 'PUT',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(updatedData),  // Send updated data to backend
          })
          .then(response => {
              if (!response.ok) {
                  throw new Error('Failed to update player.');
              }
              console.log('Player update response received:', response);

              // Update the selected player state with the new data
              setSelectedPlayer(prev => ({
                  ...prev!,
                  ...updatedData,
              }));

              // Refresh the player list and close the edit dialog
              getData();
              setEditDialogOpen(false);
          })
          .catch((error) => console.error('Error updating player:', error));
      } else {
          console.error('Failed to generate LLM description, player data not saved.');
      }
  }
};

  return (
    <Container sx={{ paddingTop: '2rem' }}>
      {/* Main heading for the app */}
      <Typography variant="h3" gutterBottom align="center" color={blue[700]}>
        Baseball Players Ranked by Hits
      </Typography>
      <Typography variant="h6" gutterBottom align="center" color={grey[600]}>
        (Recent Years First)
      </Typography>
      <Grid container spacing={4}>
        {/* List of players */}
        <Grid item xs={12} md={4}>
          <List sx={{ 
            backgroundColor: grey[100], 
            borderRadius: '8px', 
            boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.1)',
            overflowY: 'auto',
            maxHeight: '70vh'
          }}>
            {players.map((player, index) => (
              <React.Fragment key={player.id}>
                {/* Add a divider between different years */}
                {(index === 0 || player.year !== players[index - 1].year) && (
                  <Divider sx={{ margin: '0.5rem 0' }} />
                )}
                <ListItem 
                  button 
                  onClick={() => handlePlayerClick(player)} // Show player details on click
                  sx={{ 
                    padding: '1rem',
                    backgroundColor: index % 2 === 0 ? grey[50] : grey[100],
                    '&:hover': {
                      backgroundColor: blue[50],
                    },
                    borderBottom: `1px solid ${grey[300]}`,
                  }}
                >
                  <ListItemText 
                    primary={`Year: ${player.year} | Rank: ${player.rank}`} 
                    secondary={`${player.player_name}, Hits: ${player.hits}`} 
                    primaryTypographyProps={{ color: blue[900], fontWeight: 'bold' }}
                    secondaryTypographyProps={{ color: grey[800] }}
                  />
                </ListItem>
              </React.Fragment>
            ))}
          </List>
        </Grid>

        {/* Display details of the selected player */}
        {selectedPlayer && (
          <Grid item xs={12} md={8}>
            <Card sx={{ 
              borderRadius: '8px', 
              boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.1)',
              backgroundColor: grey[50]
            }}>
              <CardContent>
                <Typography variant="h5" gutterBottom color={blue[800]}>
                  {selectedPlayer.player_name}
                </Typography>
                <Typography variant="body1" paragraph color={grey[700]}>
                  {selectedPlayer.description}
                </Typography>
                <Typography variant="body2" color={grey[600]}>
                  Rank: {selectedPlayer.rank}
                </Typography>
                <Typography variant="body2" color={grey[600]}>
                  Hits: {selectedPlayer.hits}
                </Typography>
                <Typography variant="body2" color={grey[600]}>
                  Age: {selectedPlayer.age}
                </Typography>
                <Typography variant="body2" color={grey[600]}>
                  Year: {selectedPlayer.year}
                </Typography>
                <Typography variant="body2" color={grey[600]}>
                  Bats: {selectedPlayer.bats}
                </Typography>
              </CardContent>
              {/* Button to open the edit dialog */}
              <Button 
                variant="contained" 
                color="primary" 
                onClick={() => setEditDialogOpen(true)}
                sx={{ 
                  margin: '1rem',
                  backgroundColor: blue[500],
                  '&:hover': {
                    backgroundColor: blue[700],
                  }
                }}
              >
                Edit
              </Button>
            </Card>
          </Grid>
        )}
      </Grid>

      {/* Dialog for editing player details */}
      <Dialog 
        open={editDialogOpen} 
        onClose={() => setEditDialogOpen(false)} 
        fullWidth
        maxWidth="sm"
        PaperProps={{
          style: {
            position: 'fixed',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 1300,  // Ensure the dialog stays on top
            borderRadius: '8px',
            boxShadow: '0px 4px 12px rgba(0, 0, 0, 0.2)',
          },
        }}
      >
        <DialogTitle>Edit Player Details</DialogTitle>
        <DialogContent>
          {/* Input fields for editing player details */}
          <TextField
            label="Player Name"
            fullWidth
            margin="normal"
            variant="outlined"
            value={editData.player_name || ''}
            onChange={(e) => handleInputChange('player_name', e.target.value)}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            label="Age"
            fullWidth
            margin="normal"
            variant="outlined"
            type="number"
            value={editData.age || ''}
            onChange={(e) => handleInputChange('age', parseInt(e.target.value, 10))}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            label="Hits"
            fullWidth
            margin="normal"
            variant="outlined"
            type="number"
            value={editData.hits || ''}
            onChange={(e) => handleInputChange('hits', parseInt(e.target.value, 10))}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            label="Year"
            fullWidth
            margin="normal"
            variant="outlined"
            type="number"
            value={editData.year || ''}
            onChange={(e) => handleInputChange('year', parseInt(e.target.value, 10))}
            InputLabelProps={{ shrink: true }}
          />
          <TextField
            label="Bats"
            fullWidth
            margin="normal"
            variant="outlined"
            value={editData.bats || ''}
            onChange={(e) => handleInputChange('bats', e.target.value)}
            InputLabelProps={{ shrink: true }}
          />
        </DialogContent>
        <DialogActions>
          {/* Buttons to cancel or save changes */}
          <Button onClick={() => setEditDialogOpen(false)} color="secondary">
            Cancel
          </Button>
          <Button onClick={handleSave} color="primary" sx={{ backgroundColor: green[500], '&:hover': { backgroundColor: green[700] } }}>
            Save
          </Button>
        </DialogActions>
      </Dialog>
    </Container>
  );
};

export default App;
